# Generated by Django 4.0.6 on 2024-04-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome',
            field=models.CharField(default='curso sem nome', max_length=200),
            preserve_default=False,
        ),
    ]
