# Generated by Django 4.0.6 on 2024-04-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_disciplina_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='nome',
            field=models.CharField(default='sem nome', max_length=200),
            preserve_default=False,
        ),
    ]
