# Generated by Django 4.0.6 on 2024-04-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_projeto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='repositorio_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='video_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
