# Generated by Django 4.0.6 on 2024-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.FileField(upload_to='project_icons/'),
        ),
    ]
